sudo: required
language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-21
    - ANDROID_ABI=armeabi-v7a
    - ADB_INSTALL_TIMEOUT=8
android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.1
  - android-25
  - extra-android-m2repository
  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
script:
  - ./gradlew build jacocoTestReport assembleDevelopDebugAndroidTest
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI --skin WXGA720
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0.0
  - adb shell settings put global transition_animation_scale 0.0
  - adb shell settings put global animator_duration_scale 0.0
  - adb shell settings put secure show_ime_with_hard_keyboard 0
  - adb shell am broadcast -a com.android.intent.action.SET_LOCALE --es com.android.intent.extra.LOCALE EN
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - travis_wait 30 ./gradlew connectedDevelopDebugAndroidTest createDevelopDebugAndroidTestCoverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml
